<div id="tabs" >
					<ul class="der">
						<li><a href="#tabs-1"><img src="image/light/user.png" width="48" height="48"></a></li>
						<li><a href="#tabs-2"><img src="image/light/papel.png" width="48" height="48"></a></li>
					</ul>
					<div class="izq">
					<div id="tabs-1">
						<h2>Content heading 1</h2>
							<div class="col" >
    								<fieldset id="inputs">
        								nombre<input id="username" type="text" placeholder="Username" autofocus required> </br> 
        								passwd<input id="password" type="checkbox" required></br>
									passwd<input id="password" type="password" placeholder="Password" required></br>
									passwd<input id="password" type="password" placeholder="Password" required></br>
									passwd<input id="password" type="password" placeholder="Password" required></br>	
									passwd<input id="password" type="password" placeholder="Password" required></br>
    								</fieldset>
    		
							</div>
    							<fieldset id="actions">
        							<input type="submit" id="submit" value="Log in">
        						</fieldset>
							</p>
					</div>
					<!--<div id="tabs-2">
						<h2>Content heading 2</h2>
						<div class="col" >
    								<fieldset id="inputs">
        								Nombre<input id="username" type="text" placeholder="Username" autofocus required> </br> 
        								Password<input id="password" type="checkbox" required></br>
									Si <input id="checkbox" type="checkbox" placeholder="Password" required></br>
									no<input id="radio" type="radio" placeholder="Password" required></br>
									fich<input id="file" type="file" placeholder="Password" required></br>	
									e-mail<input id="email" type="email" placeholder="Password" required></br>
    								</fieldset>
    		
							</div>
    							<fieldset id="actions">
        							<input type="submit" id="submit" value="Log in">
        						</fieldset>
							</p>
					</div>-->
					</div>
					</div>



