<!-- listframe -->
<div class="xlist" id="prueba1">
	<div class="tableselector">TS</div>
	<div class="rowselector">RS</div>
	<div class="footselector">FS</div>
	<div class="frozencolscontainer">
		<div class="content">
			<div class="head"></div>
			<div class="body"></div>
			<div class="foot"></div>
		</div>
	</div>
	<div class="listcontainer">
		<div class="content">
			<div class="head"></div>
			<div class="body"></div>
			<div class="foot"></div>
		</div>
	</div>
	<div class="button maximize">MX</div>
	<div class="grip resize">RS</div>
	<div class="scrollbar frozencolshscroll">FCHS</div>
	<div class="scrollbar hscroll">HS</div>
	<div class="scrollbar vscroll">VS</div>
</div>
<!-- end listframe -->